### ISSUE TITLE
Add missing type values for Trovit

### ISSUE THREAD

**Issue by jniebuhr** [OpenEstate/OpenEstate-IO#5]
It seems that Trovit has changed their schema and now allows the values "office for sale" / "office for rent" to be in the `type` field. It should be possible to set these types.

**Comment by pinhead84** [comment]
Hello jniebuhr,

thanks for the information. Maybe there are some more changes in the Trovit schema? - But unfortunately I can't find the XSD file at <http://about.trovit.com/schemas/homes.xsd> anymore. Perhaps you know where I can find the latest schema?

**Comment by jniebuhr** [comment]
No, I've never been able to find their XSD anywhere. They just told us directly to use these values so I guess those are allowed now.

**Comment by pinhead84** [comment]
That's a real pity. I've contacted Trovit support via email. Maybe they still have a XSD for their internal workflow (e.g. validation) and they're willing to provide it to us. 

Otherwise I'm going to change [their latest known schema](https://github.com/OpenEstate/OpenEstate-IO/blob/master/Trovit/specs/homes.xsd) according to [their current documentations](https://corporate.trovit.com/feed-us-homes/) by myself. I'm afraid that the missing types are not the only modification...

**Comment by pinhead84** [comment]
Unfortunately the Trovit support did not respond to my request. I assume, they're not providing a XML schema anymore. Or maybe they don't even have a recent XML schema anymore. Even their [validation tool](https://corporate.trovit.com/validator/) is not available.

Therefore I've decided to create an [inofficial XML schema](https://github.com/OpenEstate/OpenEstate-IO/blob/5cb1a422ccb4e065578aceec1bf6b04f8267edc2/Trovit/specs/inofficial.xsd) from scratch based on [their documentation](https://corporate.trovit.com/feed-us-homes/). Unfortunately their documentations are split into several pages (in different languages), that contradict each other in some points. I've tried to find a middle way at these points. Of course we would not have those problems, if they would provide a solid schema by themselves.

Your proposed types "office for sale" / "office for rent" are also covered by the new implementation. But as I've already expected, the new schema contains a lot more changes. There are [some more types](https://github.com/OpenEstate/OpenEstate-IO/blob/5cb1a422ccb4e065578aceec1bf6b04f8267edc2/Trovit/src/main/java/org/openestate/io/trovit/xml/types/TypeValue.java#L30-L47) and new XML elements. Also there are some simplifications within the specification and the created JAXB classes.

The new implementation of Trovit-XML was pushed into the `develop` branch some minutes ago (see [commit 5cb1a42](https://github.com/OpenEstate/OpenEstate-IO/commit/5cb1a422ccb4e065578aceec1bf6b04f8267edc2)). If you're using Maven, you can use the latest snapshot version (1.4-SNAPSHOT) in order to test the new implementation as [described in the wiki](https://github.com/OpenEstate/OpenEstate-IO/wiki/Integration-with-Maven). I'm looking forward to your feedback. :)

**Comment by jniebuhr** [comment]
Thank you, I will integrate the new version today and see what they say.

**Comment by pinhead84** [comment]
Do you have any feedback about the new implementation of Trovit-XML? - Does it work for your use case? - Please let me know, if you encounter any issues. I would prefer to fix possible bugs before releasing the 1.4 version. ;)

**Comment by jniebuhr** [comment]
Hi, I’ve implemented it and the XML looks good, it’ll go to Trovit on Monday.

**Comment by pinhead84** [comment]
Thanks. Let me know, if Trovit accepts your files or if there are further fixes necessary. In the meantime - have a nice weekend. :)

**Comment by jniebuhr** [comment]
Hello, sorry it took so long. They've accepted our feed so it should be fine.
